_core:
  default_config_hash: OhypfKr4_Eo8XwXg3Sios05lN-LjxOhSdSOSkEN9Ndo
logo:
  use_default: false
  path: 'public://Herve Lewis Logo (1)_0_0.png'
brand_image:
  use_default: false
  path: 'public://herve-lewis_0.jpg'
